### ISSUE TITLE
Unclear naming

### ISSUE THREAD

**Issue by ChandlerKilpatrick1** [ebalaban/LightDarkLPDM#3]
Hi @ebalaban ,

As I am looking through LightDarkLPDM, I noticed that you copied Zach's POMDPs and didn't change the name. When you say "using LightDarkPOMDPs" are you referring to Zach's LightDarkPOMDPs or your own LightDarkLPDM version which is also named LightDarkPOMDPs in the src folder?

**Comment by ebalaban** [comment]
Should be done now.
